#!/bin/bash
#SBATCH -c 8
#SBATCH -p serial_requeue
#SBATCH --mem-per-cpu=1000

echo $FOLDER

srun -c 8 fpsync -n 8 -o "-aAx" -O "-b" "/source/filesystem/${FOLDER}/" "/destination/filesystem/${FOLDER}/"

echo $FOLDER
